# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant/playbook.yml"
    ansible.sudo = true
    ansible.verbose = false #set this to true if you want to see all the output
    ansible.limit = "all"
    ansible.config_file = "vagrant/ansible.cfg" #need to fake it out as it will find ansible.cfg which causes issues with vagrant
  end
end
